server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        # OpenAPI文档路由
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

# Swagger配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: user
        url: /v3/api-docs/user
      - name: order
        url: /v3/api-docs/order

logging:
  level:
    org.springframework.cloud.gateway: debug 